# This is a basic workflow to help you get started with Actions

name: Get currency and store

# Controls when the workflow will run
on:
  schedule:
    # 한국 시간 기준 오전 11시 1분에 실행
    - cron: '1 2 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-api-and-parse-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # 또는 원하는 Node.js 버전을 사용하세요

    - name: Install dependencies
      run: npm install

    - name: Run script to call API and parse JSON
      run: node ./scripts/api_call_and_parse.js

    # 결과 파일을 리포지토리에 커밋하는 단계
    - name: Commit and push changes
      run: |
        git config --local user.email "a01075511157@gmail.com"
        git config --local user.name "ChoSeyoung"
        git add .
        git commit -m "Add API response JSON" -a || echo "No changes to commit"
        git push
