name: Get currency and store

on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:
jobs:
  call-api-and-parse-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run script to call API and parse JSON
      run: node ./scripts/api_call_and_parse.js

    - name: Commit and push changes
      run: |
        git config --local user.email "a01075511157@gmail.com"
        git config --local user.name "ChoSeyoung"
        git add .
        git commit -m "Add API response JSON" -a || echo "No changes to commit"
        git push
